// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3NBZ6bXOGywhdd4nfsZOazBP-l9ah2VE',
    appId: '1:60035450934:web:d37f93a0ea527a7dba3097',
    messagingSenderId: '60035450934',
    projectId: 'sahabatkosku',
    authDomain: 'sahabatkosku.firebaseapp.com',
    storageBucket: 'sahabatkosku.appspot.com',
    measurementId: 'G-V394FJ28DE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCos567RomT-rVZp1MtWxXcDPv24p1IIbw',
    appId: '1:60035450934:android:1f21585583286e24ba3097',
    messagingSenderId: '60035450934',
    projectId: 'sahabatkosku',
    storageBucket: 'sahabatkosku.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoZMvEz9bUSG4mb23JWdDHEzp8srBIK8E',
    appId: '1:60035450934:ios:1681ffa391735c23ba3097',
    messagingSenderId: '60035450934',
    projectId: 'sahabatkosku',
    storageBucket: 'sahabatkosku.appspot.com',
    iosBundleId: 'com.example.sahabatkosku',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoZMvEz9bUSG4mb23JWdDHEzp8srBIK8E',
    appId: '1:60035450934:ios:1681ffa391735c23ba3097',
    messagingSenderId: '60035450934',
    projectId: 'sahabatkosku',
    storageBucket: 'sahabatkosku.appspot.com',
    iosBundleId: 'com.example.sahabatkosku',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3NBZ6bXOGywhdd4nfsZOazBP-l9ah2VE',
    appId: '1:60035450934:web:b114b5525d3e3b0eba3097',
    messagingSenderId: '60035450934',
    projectId: 'sahabatkosku',
    authDomain: 'sahabatkosku.firebaseapp.com',
    storageBucket: 'sahabatkosku.appspot.com',
    measurementId: 'G-N504NDVN2M',
  );
}
